# Nadpisuje dane logowania z application.properties - dopasowane do
# kontenera Postgresa uruchamianego przez docker-compose.dev.yml
spring.datasource.url=jdbc:postgresql://localhost:5432/financetracker
spring.datasource.username=financetracker_user
spring.datasource.password=xxxxx11111

spring.liquibase.contexts=dev